export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_POSTS = 'GET_POSTS'
export const DELETE_POST = 'DELETE_POST'
export const VOTE_POST = 'VOTE_POST'
export const SORT_POST = 'SORT_POST'
export const GET_COMMENTS = 'GET_COMMENTS'
